name: Build docker image and push to GitHub Packages

on:
  push:
    branches:
      - "develop"
    tags:
      - "*"

jobs:
  build-and-push:
    runs-on: ubuntu-18.04
    steps:

    - uses: actions/checkout@v2
  
    - name: Set env
      run: |
        if [ "${{ github.event_name }}" = "push" ] && [ ! "`echo $GITHUB_REF | grep feature`" ]; then
            echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
        else
            echo "TAG=latest" >> $GITHUB_ENV
        fi
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    
    - name: "`db-sled` build and push"
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/ktra.Dockerfile
        tags: ktra:$TAG
    
    - name: "`db-redis` build and push"
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/ktra.Dockerfile
        tags: ktra:db-redis-$TAG
        build-args: |
          DB=db-redis
    
    - name: "`db-mongo` build and push"
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/ktra.Dockerfile
        tags: ktra:db-mongo-$TAG
        build-args: |
          DB=db-mongo